# -*- coding: utf-8 -*-
"""INTERNSHIP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S09wEg3Meie0FD7HvZIsKkjAcuxlr2GM

**STEP 1: IMPORT LIBRARIES**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

"""**STEP 2: LOAD DATASET**"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/public_transport_delays.csv')

print("Dataset Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
print(df.head())

"""**STEP 3: DATA CLEANING**"""

print("\nMissing Values:")
print(df.isnull().sum())

# Remove duplicates
df = df.drop_duplicates()

print("\nDataset Shape After Cleaning:")
print(df.shape)

"""**STEP 4: EXPLORATORY DATA ANALYSIS (EDA)**"""

import matplotlib.pyplot as plt
import seaborn as sns

# Delay Distribution

plt.figure(figsize=(8,5))
sns.histplot(df['actual_arrival_delay_min'], bins=20)
plt.title("Arrival Delay Distribution")
plt.show()

"""**Weather vs Delay**"""

plt.figure(figsize=(10,5))
sns.boxplot(
    x='weather_condition',
    y='actual_arrival_delay_min',
    data=df
)
plt.xticks(rotation=45)
plt.title("Weather Condition vs Delay")
plt.show()

"""**Transport Type Analysis**"""

plt.figure(figsize=(8,5))
sns.countplot(
    x='transport_type',
    data=df
)
plt.title("Transport Type Distribution")
plt.show()

"""**Traffic Congestion Analysis**"""

plt.figure(figsize=(8,5))
sns.scatterplot(
    x='traffic_congestion_index',
    y='actual_arrival_delay_min',
    data=df
)
plt.title("Traffic Congestion vs Delay")
plt.show()

"""**Delayed vs Not Delayed**"""

plt.figure(figsize=(6,4))
sns.countplot(
    x='delayed',
    data=df
)
plt.title("Delayed vs Not Delayed")
plt.show()

"""**STEP 5: ENCODING CATEGORICAL COLUMNS**"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

"""**STEP 6: FEATURE SELECTION**"""

X = df.drop('delayed', axis=1)

y = df['delayed']

"""**STEP 7: TRAIN TEST SPLIT**"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""**STEP 8: MODEL TRAINING**"""

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

"""**STEP 9: PREDICTION**"""

y_pred = model.predict(X_test)

"""**STEP 10: EVALUATION**"""

from sklearn.metrics import accuracy_score, classification_report

accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:")
print(round(accuracy*100,2), "%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

"""**CONFUSION MATRIX**"""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""**FEATURE IMPORTANCE**"""

importance = model.feature_importances_

feature_imp = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importance
})

feature_imp = feature_imp.sort_values(
    by='Importance',
    ascending=False
)

plt.figure(figsize=(10,6))
sns.barplot(
    x='Importance',
    y='Feature',
    data=feature_imp.head(10)
)

plt.title("Top 10 Important Features")
plt.show()

print("\nTop Important Features:")
print(feature_imp.head(10))